import io
import os
import shutil

# Prevent OpenCV and underlying ML libraries from maxing out all CPU cores
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"


# rest of your main.py code
import uuid
from datetime import datetime, timezone
from typing import List

from dotenv import load_dotenv
from fastapi import FastAPI, Depends, HTTPException, status, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.security import OAuth2PasswordRequestForm
from PIL import Image

import cloudinary
import cloudinary.uploader

from database import users_collection, db
from dependencies import get_current_user, RoleChecker
from yolo_pipeline.pipeline_entry import execute_pipeline
from schemas import LoginRequest, Token, PasswordUpdate
from security import verify_password, create_access_token, get_password_hash

load_dotenv()

# Initialize FastAPI
app = FastAPI(title="LabelGuard Authentication API")

# Configure Cloudinary credentials
cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True
)

# Enable CORS for frontend requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows all origins during local development
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# RBAC permissions
require_admin = RoleChecker(["Admin"])
require_inspector_or_admin = RoleChecker(["Inspector", "Admin"])


@app.get("/")
async def serve_frontend():
    return FileResponse("index.html")


@app.get("/inspector-dashboard")
async def serve_inspector_dashboard():
    return FileResponse("inspector_dashboard.html")


@app.post("/login")
async def login(form_data: OAuth2PasswordRequestForm = Depends()):
    user = await users_collection.find_one({"employee_id": form_data.username})
    
    if not user or not verify_password(form_data.password, user["hashed_password"]):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect Employee ID or Password"
        )
        
    access_token = create_access_token(
        data={"sub": user["employee_id"], "role": user["role"]}
    )
    return {"access_token": access_token, "token_type": "bearer"}
# Add this endpoint to serve the new admin HTML file
@app.get("/admin-dashboard")
async def serve_admin_dashboard():
    return FileResponse("admin_dashboard.html")


# Route to serve the JavaScript file
@app.get("/script.js")
async def serve_script():
    return FileResponse("script.js")
# Add this endpoint to fetch YOLO scan JSON data to populate the Repository table
@app.get("/api/scans", dependencies=[Depends(RoleChecker(["Admin", "Inspector"]))])
async def get_all_scans(current_user: dict = Depends(get_current_user)):
    # Fetch all scans generated by the YOLO pipeline from MongoDB
    cursor = db["scans"].find().sort("timestamp", -1).limit(50)
    scans_list = []
    
    async for document in cursor:
        document["_id"] = str(document["_id"]) # convert ObjectId to string
        scans_list.append(document)
        
    return scans_list

@app.post("/api/analyze-scan", dependencies=[Depends(require_inspector_or_admin)])
async def analyze_scan(
    images: List[UploadFile] = File(...),
    current_user: dict = Depends(get_current_user)
):
    if not images:
        raise HTTPException(status_code=400, detail="No images uploaded")

    # 1. Create a unique temporary directory for labels/crops output
    scan_id = f"scan_{uuid.uuid4().hex[:8]}"
    temp_dir = f"./temp_processing/{scan_id}"

    # Route uploaded images into yolo_pipeline/images/ so YOLO can always find them
    # We resolve the absolute path relative to this file to avoid CWD ambiguity
    YOLO_PIPELINE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "yolo_pipeline")
    images_dir = os.path.join(YOLO_PIPELINE_DIR, "images")

    # Clear any images from previous scans so YOLO only sees the current upload
    if os.path.exists(images_dir):
        shutil.rmtree(images_dir)
    os.makedirs(images_dir, exist_ok=True)

    # Create temp output folders for labels and crops
    os.makedirs(os.path.join(temp_dir, "labels"), exist_ok=True)
    os.makedirs(os.path.join(temp_dir, "crops"), exist_ok=True)

    cloud_urls = []

    try:
        # 2. Save uploaded files locally to the images/ folder & upload to Cloudinary
        for image in images:
            file_bytes = await image.read()

            # Save locally for YOLO/OCR process
            #local_path = os.path.join(images_dir, image.filename)
            local_path = os.path.join(images_dir, os.path.basename(image.filename))
            with open(local_path, "wb") as f:
                f.write(file_bytes)

            # Upload to Cloudinary (minimal original code)
            try:
                uploaded_result = cloudinary.uploader.upload(
                    file_bytes, folder="labelguard_scans"
                )
                cloud_urls.append(uploaded_result.get("secure_url"))
            except Exception as upload_err:
                # Cloud upload failed but local file is saved — pipeline can still run
                print(f"[WARNING] Cloudinary upload failed for {image.filename}: {upload_err}")
                cloud_urls.append(None)  # placeholder so index alignment is preserved

        # 3. Run the new YOLO + OCR Pipeline
        # Pass images_dir explicitly so pipeline knows where images live
        extracted_details = execute_pipeline(temp_dir, images_dir)

        # 4. Store record in MongoDB Cloud ('scans' collection)
        scan_document = {
            "scan_id": scan_id,
            "inspector_id": current_user.get("employee_id") or current_user.get("sub"),
            "timestamp": datetime.now(timezone.utc),
            "cloud_image_urls": cloud_urls,
            "extracted_details": extracted_details,
            "status": "Pending Review"
        }
        db_result = await db["scans"].insert_one(scan_document)

        # 5. Return response to UI
        return {
            "status": "success",
            "mongo_id": str(db_result.inserted_id),
            "scan_id": scan_id,
            "cloud_urls": cloud_urls,
            "extracted_details": extracted_details
        }

    finally:
        # 6. Clean temporary disk folder
        if os.path.exists(temp_dir):
            shutil.rmtree(temp_dir)

@app.get("/api/officer-requests", dependencies=[Depends(require_admin)])
async def get_officer_requests(current_user: dict = Depends(get_current_user)):
    # Find all inspectors whose account status is 'pending'
    # Using your existing users_collection
    cursor = users_collection.find({"role": "Inspector", "status": "pending"})
    
    requests_list = []
    async for user in cursor:
        user["_id"] = str(user["_id"]) # Convert ObjectId to string
        # Exclude password hash before sending to frontend
        user.pop("hashed_password", None) 
        requests_list.append(user)
        
    return requests_list
@app.get("/api/admin-dashboard", dependencies=[Depends(require_admin)])
async def admin_dashboard():
    return {"message": "Welcome Admin. Access granted."}


@app.get("/api/inspections", dependencies=[Depends(require_inspector_or_admin)])
async def get_inspections(current_user: dict = Depends(get_current_user)):
    return {
        "message": "Access granted.",
        "employee_id": current_user["employee_id"],
        "role": current_user["role"]
    }


@app.put("/api/update-password")
async def update_password(
    payload: PasswordUpdate,
    current_user: dict = Depends(get_current_user)
):
    hashed_password = get_password_hash(payload.new_password)
    
    result = await users_collection.update_one(
        {"employee_id": current_user["employee_id"]},
        {"$set": {"hashed_password": hashed_password}}
    )
    
    if result.modified_count == 0:
        raise HTTPException(status_code=400, detail="Password update failed.")
        
    return {
        "message": f"Password successfully updated for user {current_user['employee_id']} ({current_user['role']})"
    }