import os
import sys
import json
import glob
from pathlib import Path

# Add current directory to sys.path so sub-modules (scaling, masking, etc.) 
# can import config and each other seamlessly inside FastAPI
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
if CURRENT_DIR not in sys.path:
    sys.path.insert(0, CURRENT_DIR)

import config
import scaling
import masking
import ocr
import measurement
from models import run_delegated_models


def process_ocr_and_scaling(temp_dir: str, images_dir: str) -> dict:
    """Runs the OCR and Scaling logic on the JSONs generated by YOLO."""
    master_product_data = {
        "product_report": [],
        "total_images_processed": 0
    }
    
    #json_files = glob.glob(os.path.join(config.OUTPUT_DIR, "*.json"))
    dynamic_labels_dir = os.path.join(temp_dir, "labels")
    json_files = glob.glob(os.path.join(dynamic_labels_dir, "*.json"))
    for json_path in json_files:
        with open(json_path, 'r') as f:
            yolo_data = json.load(f)
            
        image_filename = yolo_data.get("image_file")
        if not image_filename:
            continue
        # Use the explicit images_dir so we always look in the right folder
        image_path = os.path.join(images_dir, image_filename)
        
        if not os.path.exists(image_path):
            continue

        pixels_per_metric = scaling.calculate_pixels_per_metric(image_path)
        if pixels_per_metric is None:
            continue
            
        image_results = {
            "image": image_filename,
            "scale_pixels_per_mm": round(pixels_per_metric, 2),
            "fields": []
        }
        
        for detection in yolo_data.get("detections", []):
            class_name = detection["class_name"]
            
            if class_name == "PRINCIPAL_DISPLAY_PANEL":
                print(f"  -> Measuring Panel Size: {class_name} (Skipping OCR)")
                bbox = detection["bbox_pixels"]
                panel_px_width = bbox["x_max"] - bbox["x_min"]
                panel_px_height = bbox["y_max"] - bbox["y_min"]
                
                real_w, real_h = measurement.calculate_real_size(panel_px_width, panel_px_height, pixels_per_metric)
                
                image_results["fields"].append({
                    "class_name": class_name,
                    "type": "panel_dimensions",
                    "physical_width_mm": round(real_w, 2),
                    "physical_height_mm": round(real_h, 2)
                })

            else:
                masked_image = masking.generate_masked_roi(image_path, [detection], class_name)
                
                if masked_image is not None:
                    ocr_results = ocr.extract_and_measure_text(masked_image)
                    field_texts = []
                    
                    for item in ocr_results:
                        real_w, real_h = measurement.calculate_real_size(item["pixel_width"], item["pixel_height"], pixels_per_metric)
                        field_texts.append({
                            "text": item["text"],
                            "confidence": round(item["confidence"], 3),
                            "physical_width_mm": round(real_w, 2),
                            "physical_height_mm": round(real_h, 2)
                        })
                    
                    image_results["fields"].append({
                        "class_name": class_name,
                        "type": "text_extraction",
                        "extracted_data": field_texts
                    })

        master_product_data["product_report"].append(image_results)
        master_product_data["total_images_processed"] += 1

    # Save final consolidated output (persistent location so it survives temp_dir cleanup)
    master_json_path = "final_product_analysis.json"
    with open(master_json_path, 'w') as f:
        json.dump(master_product_data, f, indent=4)
        
    print(f"\nPIPELINE COMPLETE! Master JSON saved to: {master_json_path}")
    return master_product_data


def execute_pipeline(temp_dir: str, images_dir: str) -> dict:
    """
    Main orchestrator called by FastAPI main.py.
    images_dir: absolute path where uploaded images were saved (yolo_pipeline/images/).
    temp_dir:   path for this scan's labels/crops/final JSON output.
    """
    # 1. Set config paths — images come from the dedicated yolo_pipeline/images/ folder
    config.BASE_DIR = temp_dir
    config.SOURCE_PATH = images_dir                          # <- uploaded images live here
    config.OUTPUT_DIR = os.path.join(temp_dir, "labels")
    config.CROPS_OUTPUT_DIR = os.path.join(temp_dir, "crops")

    # Ensure output folders exist (images_dir already created by main.py)
    os.makedirs(config.OUTPUT_DIR, exist_ok=True)
    os.makedirs(config.CROPS_OUTPUT_DIR, exist_ok=True)

    # 2. Phase 1: YOLO Generation
    print("--- STARTING YOLO PHASE ---")
    generated_jsons = run_delegated_models(
        model_configs=config.MODEL_CONFIGS,
        source=config.SOURCE_PATH,
        output_dir=config.OUTPUT_DIR,
        crops_out_dir=config.CROPS_OUTPUT_DIR,
        conf=getattr(config, 'CONFIDENCE', 0.25),
        save_crops=getattr(config, 'SAVE_CROPS', True),
    )

    # 3. Phase 2: OCR and Scaling
    print(f"[PHASE 1] YOLO wrote {len(generated_jsons)} JSON files: {generated_jsons}")
    print("--- STARTING OCR AND SCALING PHASE ---")
    report = process_ocr_and_scaling(temp_dir, images_dir)
    return report